/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001c3b",
        "on-primary-container": "#8aa4cf",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "on-tertiary": "#ffffff",
        "background": "#f8f9fa",
        "inverse-primary": "#adc8f5",
        "on-primary": "#ffffff",
        "surface-tint": "#455f87",
        "tertiary": "#341f00",
        "primary-fixed": "#d5e3ff",
        "tertiary-container": "#503300",
        "outline": "#74777f",
        "error": "#ba1a1a",
        "on-tertiary-container": "#c69b5f",
        "on-surface-variant": "#43474e",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed-variant": "#633f00",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#adc8f5",
        "secondary-fixed-dim": "#ffb955",
        "secondary-fixed": "#ffddb4",
        "tertiary-fixed-dim": "#edbf7f",
        "outline-variant": "#c4c6cf",
        "primary-container": "#1e3a5f",
        "on-secondary": "#ffffff",
        "primary": "#022448",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#ffddb2",
        "on-surface": "#191c1d",
        "on-secondary-container": "#6b4500",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#291800",
        "secondary-container": "#feae2c",
        "surface-bright": "#f8f9fa",
        "secondary": "#835500",
        "surface-container": "#edeeef",
        "on-primary-fixed-variant": "#2d486d",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#60410c",
        // Login page colors kept for compatibility
        "on-secondary-container-green": "#167249",
        "surface-container-low-green": "#f1f4f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};