-- Run once in Supabase SQL Editor before enabling section management.
-- Existing grade-level assignments remain unsectioned until placed by the principal.
create table if not exists public.grade_section (
  section_id bigint generated by default as identity primary key,
  gl_id integer not null references public.grade_level(gl_id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 80),
  teacher_id integer references public.teacher(teacher_id) on delete set null,
  created_at timestamptz not null default now(),
  unique (section_id, gl_id)
);

create unique index if not exists grade_section_grade_name_ci
  on public.grade_section (gl_id, lower(btrim(name)));

alter table public.student add column if not exists section_id bigint;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'student_section_grade_fk') then
    alter table public.student add constraint student_section_grade_fk
      foreign key (section_id, gl_id)
      references public.grade_section(section_id, gl_id);
  end if;
end $$;

create index if not exists student_section_id_idx on public.student(section_id);
create index if not exists grade_section_teacher_id_idx on public.grade_section(teacher_id);

-- Preserve section placement when switching between school years. The student's
-- section_id is the active pointer; this table keeps per-year placements.
create table if not exists public.student_section_assignment (
  student_id integer not null references public.student(student_id) on delete cascade,
  gl_id integer not null references public.grade_level(gl_id) on delete cascade,
  section_id bigint not null,
  assigned_at timestamptz not null default now(),
  primary key (student_id, gl_id),
  foreign key (section_id, gl_id) references public.grade_section(section_id, gl_id) on delete cascade
);

create index if not exists student_section_assignment_section_idx on public.student_section_assignment(section_id);

alter table public.grade_section enable row level security;
grant select, insert, update, delete on public.grade_section to service_role;
grant select on public.grade_section to authenticated;
grant usage, select on sequence public.grade_section_section_id_seq to service_role;
alter table public.student_section_assignment enable row level security;
grant select, insert, update, delete on public.student_section_assignment to service_role;
grant select on public.student_section_assignment to authenticated;
